apiVersion: kargo.akuity.io/v1alpha1
kind: Warehouse
metadata:
  name: ingress-nginx
  namespace: platform-addons
spec:
  subscriptions:
  - chart:
      # Classic (HTTP) Helm repo: repoURL + chart name.
      repoURL: https://kubernetes.github.io/ingress-nginx
      name: ingress-nginx
      semverConstraint: ^4.14.0
