apiVersion: argocd.akuity.io/v1alpha1
kind: ArgoCD
metadata:
  name: my-argocd-instance
spec:
  description: "Argo CD Instance for Kargo Quickstart"
  instanceSpec: {}
  version: v3.4.3
---
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
  name: argocd-cm
data:
  accounts.admin: login
  helm.enabled: "true"
  kustomize.enabled: "true"
---
apiVersion: v1
kind: Secret
metadata:
  name: argocd-secret
  namespace: argocd
  labels:
    app.kubernetes.io/name: argocd-secret
    app.kubernetes.io/part-of: argocd
type: Opaque
data:
  # bcrypt hash of the admin password, akuity-argocd
  # `argocd account bcrypt --password akuity-argocd | base64`
  admin.password: 'JDJhJDEwJGRScWVZcWJwQzF5M0FpTFA1bjF1U08xTXBuUUxWWG9vWXdJbjNOYWpVNExTajI1Y2dTd2pl'
