apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: dev
  namespace: kargo-simple
  annotations:
    kargo.akuity.io/color: red
spec:
  requestedFreight:
  - origin:
      kind: Warehouse
      name: guestbook
    sources:
      direct: true
  promotionTemplate:
    spec:
      vars:
      - name: gitRepo
        value: https://github.com/madmatt112/here-be-akuity
      - name: imageRepo
        value: ghcr.io/madmatt112/guestbook
      - name: env
        value: dev
      - name: targetBranch
        value: env/dev
      steps:
      - uses: git-clone
        config:
          repoURL: ${{ vars.gitRepo }}
          checkout:
          - branch: main
            path: ./src
          - branch: ${{ vars.targetBranch }}
            create: true
            path: ./out
      - uses: git-clear
        config:
          path: ./out
      - uses: kustomize-set-image
        as: update-image
        config:
          path: ./src/app/quickstart/guestbook/env/${{ vars.env }}
          images:
          - image: ${{ vars.imageRepo }}
            tag: ${{ imageFrom(vars.imageRepo).Tag }}
      - uses: kustomize-build
        config:
          path: ./src/app/quickstart/guestbook/env/${{ vars.env }}
          outPath: ./out/manifests.yaml
      - uses: git-commit
        as: commit
        config:
          path: ./out
          message: ${{ outputs['update-image'].commitMessage }}
      - uses: git-push
        config:
          path: ./out
          targetBranch: ${{ vars.targetBranch }}
      - uses: argocd-update
        config:
          apps:
          - selector:
              matchLabels:
                app: guestbook
                env: ${{ vars.env }}
            sources:
            - repoURL: ${{ vars.gitRepo }}
              desiredRevision: ${{ outputs.commit.commit }}
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: prod
  namespace: kargo-simple
spec:
  requestedFreight:
  - origin:
      kind: Warehouse
      name: guestbook
    sources:
      stages:
      - dev
  promotionTemplate:
    spec:
      vars:
      - name: gitRepo
        value: https://github.com/madmatt112/here-be-akuity
      - name: imageRepo
        value: ghcr.io/madmatt112/guestbook
      - name: env
        value: prod
      - name: targetBranch
        value: env/prod
      steps:
      - uses: git-clone
        config:
          repoURL: ${{ vars.gitRepo }}
          checkout:
          - branch: main
            path: ./src
          - branch: ${{ vars.targetBranch }}
            create: true
            path: ./out
      - uses: git-clear
        config:
          path: ./out
      - uses: kustomize-set-image
        as: update-image
        config:
          path: ./src/app/quickstart/guestbook/env/${{ vars.env }}
          images:
          - image: ${{ vars.imageRepo }}
            tag: ${{ imageFrom(vars.imageRepo).Tag }}
      - uses: kustomize-build
        config:
          path: ./src/app/quickstart/guestbook/env/${{ vars.env }}
          outPath: ./out/manifests.yaml
      - uses: git-commit
        as: commit
        config:
          path: ./out
          message: ${{ outputs['update-image'].commitMessage }}
      - uses: git-push
        config:
          path: ./out
          targetBranch: ${{ vars.targetBranch }}
      - uses: argocd-update
        config:
          apps:
          - selector:
              matchLabels:
                app: guestbook
                env: ${{ vars.env }}
            sources:
            - repoURL: ${{ vars.gitRepo }}
              desiredRevision: ${{ outputs.commit.commit }}
